# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'WayMap' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
  # Pods for WayMap

  target 'WayMapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WayMapUITests' do
    inherit! :search_paths
    # Pods for testing
  end



end
